language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.4
    dist: trusty
    before_install:
      - python3 -m pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 python3 -m pip install -U
  - os: linux
    sudo: required
    python: 3.5
    dist: trusty
    before_install:
      - python3 -m pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 python3 -m pip install -U
  - os: linux
    sudo: required
    python: 3.6
    dist: trusty
    before_install:
      - python3 -m pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 python3 -m pip install -U
  - os: linux
    sudo: required
    python: 3.7
    dist: xenial
    before_install:
      - python3 -m pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 python3 -m pip install -U
  - os: osx
    language: generic
    before_install:
    - travis_wait brew update
    - pip install virtualenv
    - virtualenv env -p python3
    - source env/bin/activate
    - alias pip="pip3"
  - os: osx
    language: generic
    before_install:
    - travis_wait brew update
    - brew upgrade python
    - pip install virtualenv
    - virtualenv env -p python3
    - source env/bin/activate
    - alias pip="pip3"
install:
  - "python3 -m pip install --upgrade pip setuptools"
  - "python3 setup.py install"
script:
  - "python3 tests/decode_token.py"
  - "python3 tests/get_show_no_token.py"
  - "python3 tests/get_users_me_token.py"
  - "python3 tests/websocket_demo.py"
  - "python3 tests/websocket_event.py"